'use client';

import { Suspense, useEffect, useState } from 'react';
import { useRouter, useSearchParams } from 'next/navigation';
import { Button, Input, Label } from '@atlas/ui';
import { apiRequest } from '@/lib/api-client';
import { getSupabaseBrowserClient } from '@/lib/supabase-browser';

/**
 * Customer Portal login — customer-portal-prd.md. Single page handling
 * both states: the initial email-request form, and (when `token_hash`/
 * `type` query params are present — the link generated by
 * `consolePortalMagicLinkNotifier`) automatic client-side OTP
 * verification via Supabase's own `auth.verifyOtp`, which establishes
 * the real `auth.uid()` session RLS relies on, then
 * `/api/v1/portal/auth/complete` to link every matching Contact.
 */
export default function PortalLoginPage(): JSX.Element {
  return (
    <Suspense fallback={null}>
      <PortalLoginContent />
    </Suspense>
  );
}

function PortalLoginContent(): JSX.Element {
  const searchParams = useSearchParams();
  const router = useRouter();
  const tokenHash = searchParams.get('token_hash');
  const type = searchParams.get('type');

  const [email, setEmail] = useState('');
  const [requested, setRequested] = useState(false);
  const [verifying, setVerifying] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    if (!tokenHash || type !== 'magiclink') return;
    setVerifying(true);
    setError(null);
    (async () => {
      const supabase = getSupabaseBrowserClient();
      const { error: verifyError } = await supabase.auth.verifyOtp({
        token_hash: tokenHash,
        type: 'magiclink',
      });
      if (verifyError) {
        setError(verifyError.message);
        setVerifying(false);
        return;
      }
      try {
        await apiRequest('/api/v1/portal/auth/complete', { method: 'POST' });
        router.push('/portal');
      } catch (err) {
        setError(err instanceof Error ? err.message : 'Failed to complete Portal login.');
        setVerifying(false);
      }
    })().catch((err: unknown) => {
      setError(err instanceof Error ? err.message : 'Failed to verify login link.');
      setVerifying(false);
    });
  }, [tokenHash, type, router]);

  const requestLink = async (event: React.FormEvent) => {
    event.preventDefault();
    setError(null);
    try {
      await apiRequest('/api/v1/portal/auth/request-link', {
        method: 'POST',
        body: JSON.stringify({ email }),
      });
      setRequested(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Failed to request a login link.');
    }
  };

  if (tokenHash) {
    return (
      <main className="mx-auto max-w-sm p-8 text-center">
        {error ? (
          <p className="text-sm text-red-600">{error}</p>
        ) : (
          <p className="text-muted-foreground text-sm">
            {verifying ? 'Signing you in…' : 'Redirecting…'}
          </p>
        )}
      </main>
    );
  }

  return (
    <main className="mx-auto max-w-sm p-8">
      <h1 className="mb-6 text-2xl font-semibold">Customer Portal</h1>
      {requested ? (
        <p className="text-muted-foreground text-sm">
          If that email is registered for Portal access, a login link has been sent.
        </p>
      ) : (
        <form onSubmit={requestLink} className="flex flex-col gap-3">
          <div>
            <Label htmlFor="email">Email</Label>
            <Input
              id="email"
              type="email"
              required
              value={email}
              onChange={(event) => setEmail(event.target.value)}
            />
          </div>
          {error ? <p className="text-sm text-red-600">{error}</p> : null}
          <Button type="submit">Send login link</Button>
        </form>
      )}
    </main>
  );
}
