import { sql } from 'drizzle-orm';
import {
  boolean,
  check,
  integer,
  jsonb,
  pgSchema,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { organizations, teams } from './org';
import { customers, contacts } from './crm';
import { properties, assets } from './properties';
import { tradeTypes } from './reference';
import { users } from './identity';

/**
 * Jobs, Scheduling & Dispatch domain — see docs/03-domain/jobs.md,
 * docs/03-domain/tasks.md, docs/03-domain/scheduling.md,
 * docs/03-domain/dispatch.md, docs/06-modules/jobs-prd.md,
 * docs/06-modules/scheduling-prd.md, docs/06-modules/dispatch-prd.md,
 * docs/13-roadmap/sprint-4.md. Maps to two TypeScript packages
 * (@atlas/jobs, @atlas/scheduling — scaffolded separately since Sprint 0,
 * package.json descriptions: "Jobs and Tasks" / "Scheduling and
 * Dispatch") sharing one Postgres schema, per docs/04-database/
 * schema-overview.md's single "`jobs` schema" grouping and
 * docs/02-architecture/component-architecture.md's single "jobs" module
 * (owns jobs, tasks, scheduling, dispatch) — the same two-packages/
 * one-module resolution used for @atlas/properties + @atlas/assets in
 * Sprint 3 (see SPRINT-3-COMPLETION-REPORT.md, "Architecture
 * Decisions").
 *
 * `search_vector` columns are not modeled here — same reasoning as
 * schema/crm.ts and schema/properties.ts: hand-written in the RLS/search
 * migration, not generated by Drizzle Kit.
 */
export const jobsSchema = pgSchema('jobs');

export const jobStatusEnum = jobsSchema.enum('job_status', [
  'draft',
  'scheduled',
  'dispatched',
  'in_progress',
  'on_hold',
  'completed',
  'cancelled',
]);

export const jobPriorityEnum = jobsSchema.enum('job_priority', ['normal', 'urgent', 'emergency']);

export const jobSourceEnum = jobsSchema.enum('job_source', [
  'phone',
  'portal',
  'repeat_visit',
  'marketplace',
]);

export const taskTypeEnum = jobsSchema.enum('task_type', [
  'checkbox',
  'text',
  'number',
  'photo',
  'signature',
  'select',
]);

/**
 * The kind of work — docs/03-domain/domain-overview.md#the-trade-agnostic-configuration-pattern.
 * `organization_id IS NULL` means a platform-provided default, mirroring
 * `properties.asset_types`' precedent exactly.
 */
export const jobTypes = jobsSchema.table(
  'job_types',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id').references(() => organizations.id),
    tradeTypeId: uuid('trade_type_id').references(() => tradeTypes.id),
    name: text('name').notNull(),
    defaultDurationMinutes: integer('default_duration_minutes'),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_job_types_org_trade_name').on(
      table.organizationId,
      table.tradeTypeId,
      table.name,
    ),
  ],
);

/** Pricing/reporting grouping above Job Type — domain-overview.md. Platform defaults follow the same `organization_id IS NULL` pattern. */
export const serviceCategories = jobsSchema.table(
  'service_categories',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id').references(() => organizations.id),
    name: text('name').notNull(),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex('uq_service_categories_org_name').on(table.organizationId, table.name)],
);

/**
 * A Job Type's default checklist — docs/03-domain/tasks.md. One template
 * per Job Type (`job_type_id` unique); `organization_id` is denormalized
 * from the parent Job Type for direct RLS filtering, matching the
 * `properties.rooms`-through-`buildings` precedent.
 */
export const checklistTemplates = jobsSchema.table('checklist_templates', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id').references(() => organizations.id),
  jobTypeId: uuid('job_type_id')
    .notNull()
    .unique()
    .references(() => jobTypes.id),
  name: text('name').notNull(),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/** Individual template steps, copied onto a Job's `tasks` at creation — tasks.md business rule 1. */
export const checklistTemplateItems = jobsSchema.table('checklist_template_items', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id').references(() => organizations.id),
  checklistTemplateId: uuid('checklist_template_id')
    .notNull()
    .references(() => checklistTemplates.id),
  label: text('label').notNull(),
  type: taskTypeEnum('type').notNull(),
  isRequired: boolean('is_required').notNull().default(true),
  sortOrder: integer('sort_order').notNull().default(0),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Server-authoritative, per-Organization sequential Job numbering —
 * jobs.md "Key attributes": "job_number (Organization-scoped,
 * human-readable, sequential)". Incremented via a race-free atomic
 * UPSERT (`INSERT ... ON CONFLICT DO UPDATE ... RETURNING`), never
 * `SELECT MAX(job_number) + 1` — see @atlas/jobs's
 * `infrastructure/job-number.ts`. RLS-gated identically to `jobs` INSERT
 * (`jobs:write`) since only a Job-creating transaction ever touches it;
 * see the RLS/audit migration.
 */
export const jobNumberCounters = jobsSchema.table('job_number_counters', {
  organizationId: uuid('organization_id')
    .primaryKey()
    .references(() => organizations.id),
  nextNumber: integer('next_number').notNull().default(1),
});

/**
 * The central operational entity — docs/03-domain/jobs.md. `propertyId`
 * is required (business rule 1); an Organization-level placeholder
 * Property for non-address work is not implemented this sprint — see
 * SPRINT-4-COMPLETION-REPORT.md, "Known Limitations". `jobTypeId` is
 * required: it is what drives the checklist, so a Job with no Job Type
 * would have no documented way to acquire one.
 */
export const jobs = jobsSchema.table(
  'jobs',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    jobNumber: integer('job_number').notNull(),
    jobTypeId: uuid('job_type_id')
      .notNull()
      .references(() => jobTypes.id),
    serviceCategoryId: uuid('service_category_id').references(() => serviceCategories.id),
    status: jobStatusEnum('status').notNull().default('draft'),
    priority: jobPriorityEnum('priority').notNull().default('normal'),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id),
    propertyId: uuid('property_id')
      .notNull()
      .references(() => properties.id),
    contactId: uuid('contact_id').references(() => contacts.id),
    description: text('description'),
    source: jobSourceEnum('source').notNull().default('phone'),
    cancellationReason: text('cancellation_reason'),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_jobs_organization_id_job_number').on(table.organizationId, table.jobNumber),
  ],
);

/** Job <-> Asset join — jobs.md: "References zero or more Assets." */
export const jobAssets = jobsSchema.table(
  'job_assets',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    jobId: uuid('job_id')
      .notNull()
      .references(() => jobs.id),
    assetId: uuid('asset_id')
      .notNull()
      .references(() => assets.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex('uq_job_assets_job_id_asset_id').on(table.jobId, table.assetId)],
);

/**
 * Job <-> Technician (User) join — jobs.md: "Has many Technician
 * assignments (`job_assignments`)." The source of truth for
 * `jobs:read_assigned`/`jobs:write_assigned` scoping (see
 * docs/03-domain/technicians.md business rule 2: "references a User
 * directly, not a separate Technician ID").
 */
export const jobAssignments = jobsSchema.table(
  'job_assignments',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    jobId: uuid('job_id')
      .notNull()
      .references(() => jobs.id),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id),
    assignedByUserId: uuid('assigned_by_user_id').references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [uniqueIndex('uq_job_assignments_job_id_user_id').on(table.jobId, table.userId)],
);

/** Append-only Job status-transition log — jobs.md Data requirements; feeds Audit Events, and is the fast denormalized log the UI reads directly. */
export const jobStatusHistory = jobsSchema.table('job_status_history', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  jobId: uuid('job_id')
    .notNull()
    .references(() => jobs.id),
  fromStatus: jobStatusEnum('from_status'),
  toStatus: jobStatusEnum('to_status').notNull(),
  reason: text('reason'),
  changedByUserId: uuid('changed_by_user_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * A Job's checklist item, copied from a `checklist_template_items` row
 * at Job creation (or added ad hoc) — docs/03-domain/tasks.md.
 * `checklistTemplateItemId` is nullable: ad hoc Tasks have no template
 * origin.
 */
export const tasks = jobsSchema.table('tasks', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  jobId: uuid('job_id')
    .notNull()
    .references(() => jobs.id),
  checklistTemplateItemId: uuid('checklist_template_item_id').references(
    () => checklistTemplateItems.id,
  ),
  label: text('label').notNull(),
  type: taskTypeEnum('type').notNull(),
  isRequired: boolean('is_required').notNull().default(true),
  sortOrder: integer('sort_order').notNull().default(0),
  responseValue: jsonb('response_value'),
  completedByUserId: uuid('completed_by_user_id').references(() => users.id),
  completedAt: timestamp('completed_at', { withTimezone: true }),
  overrideReason: text('override_reason'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * A Job's time window + Technician assignment — docs/03-domain/
 * scheduling.md. `jobId` is unique: "a Job has at most one active
 * `schedule_event`; rescheduling updates it and logs history rather than
 * creating a competing record."
 */
export const scheduleEvents = jobsSchema.table(
  'schedule_events',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    jobId: uuid('job_id')
      .notNull()
      .unique()
      .references(() => jobs.id),
    scheduledStart: timestamp('scheduled_start', { withTimezone: true }).notNull(),
    scheduledEnd: timestamp('scheduled_end', { withTimezone: true }).notNull(),
    teamId: uuid('team_id').references(() => teams.id),
    notes: text('notes'),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    check(
      'chk_schedule_events_end_after_start',
      sql`${table.scheduledEnd} > ${table.scheduledStart}`,
    ),
  ],
);

/** Schedule Event <-> Technician (User) join — scheduling.md: "assigned_user_ids (one or more Technicians)." */
export const scheduleEventAssignments = jobsSchema.table(
  'schedule_event_assignments',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    scheduleEventId: uuid('schedule_event_id')
      .notNull()
      .references(() => scheduleEvents.id),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_schedule_event_assignments_event_id_user_id').on(
      table.scheduleEventId,
      table.userId,
    ),
  ],
);

/** Append-only reschedule log — scheduling.md: "Reschedule history (previous windows, reason)." */
export const scheduleEventHistory = jobsSchema.table('schedule_event_history', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  scheduleEventId: uuid('schedule_event_id')
    .notNull()
    .references(() => scheduleEvents.id),
  jobId: uuid('job_id')
    .notNull()
    .references(() => jobs.id),
  previousStart: timestamp('previous_start', { withTimezone: true }).notNull(),
  previousEnd: timestamp('previous_end', { withTimezone: true }).notNull(),
  reason: text('reason'),
  changedByUserId: uuid('changed_by_user_id').references(() => users.id),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Dispatch lifecycle timestamps — docs/03-domain/dispatch.md: "a
 * forward-only sequence of optional timestamps, not a formal enumerated
 * state machine." Not unique on `jobId`: a Job may be dispatched more
 * than once over its life (e.g., re-dispatch after a reschedule
 * supersedes an unacknowledged dispatch — dispatch-prd.md, Edge cases).
 * The "current" dispatch is the most recent row by `dispatchedAt`.
 */
export const dispatchEvents = jobsSchema.table('dispatch_events', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  jobId: uuid('job_id')
    .notNull()
    .references(() => jobs.id),
  dispatchedAt: timestamp('dispatched_at', { withTimezone: true }).notNull().defaultNow(),
  dispatchedByUserId: uuid('dispatched_by_user_id').references(() => users.id),
  acknowledgedAt: timestamp('acknowledged_at', { withTimezone: true }),
  enRouteAt: timestamp('en_route_at', { withTimezone: true }),
  arrivedAt: timestamp('arrived_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
