import { sql } from 'drizzle-orm';
import {
  boolean,
  date,
  integer,
  numeric,
  pgSchema,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { organizations } from './org';
import { customers } from './crm';
import { tradeTypes } from './reference';

/**
 * Properties & Assets domain: the physical/service context tied to
 * Customers — see docs/03-domain/properties.md, docs/03-domain/
 * buildings.md, docs/03-domain/rooms.md, docs/03-domain/assets.md,
 * docs/06-modules/properties-prd.md, docs/06-modules/assets-prd.md,
 * docs/13-roadmap/sprint-3.md. Maps to two TypeScript packages
 * (@atlas/properties, @atlas/assets — see packages/*\/package.json,
 * scaffolded separately since Sprint 0) sharing one Postgres schema, per
 * docs/04-database/schema-overview.md's grouping.
 *
 * `search_vector` columns are not modeled here — same reasoning as
 * packages/database/src/schema/crm.ts: their DDL lives in the
 * hand-written RLS/search migration, not generated by Drizzle Kit.
 *
 * All six tables here carry `organization_id` directly (not purely
 * inherited through a join), matching the `crm.contacts` precedent from
 * Sprint 2: every one of them is independently audited, and
 * docs/04-database/indexes.md principle 2 expects a direct, indexed
 * `organization_id` regardless of how many parent joins away the actual
 * ownership chain runs (Asset -> Room -> Building -> Property ->
 * Organization is four joins deep — RLS and the generic audit trigger
 * both need this to stay a single-table check, not a four-way join).
 */
export const propertiesSchema = pgSchema('properties');

export const propertyTypeEnum = propertiesSchema.enum('property_type', [
  'residential_single_family',
  'residential_multi_unit',
  'commercial',
]);

export const buildingTypeEnum = propertiesSchema.enum('building_type', [
  'main',
  'detached_garage',
  'outbuilding',
  'unit',
]);

export const roomTypeEnum = propertiesSchema.enum('room_type', [
  'kitchen',
  'bathroom',
  'utility',
  'attic',
  'basement',
  'garage',
  'other',
]);

export const assetStatusEnum = propertiesSchema.enum('asset_status', [
  'active',
  'removed',
  'decommissioned',
]);

/**
 * A physical location — durable and independent of any single Customer
 * relationship, per docs/03-domain/properties.md business rule 1. No
 * `customer_id` column: the current/historical Customer relationship is
 * entirely represented by `property_customer_associations`, per that
 * document's own Data Requirements line — a Property that has never been
 * associated with any Customer is a valid, meaningful state (e.g.,
 * bulk-imported from a service-area survey).
 */
export const properties = propertiesSchema.table('properties', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  propertyType: propertyTypeEnum('property_type').notNull(),
  addressLine1: text('address_line1').notNull(),
  addressLine2: text('address_line2'),
  addressCity: text('address_city'),
  addressRegion: text('address_region'),
  addressPostalCode: text('address_postal_code'),
  addressCountry: text('address_country'),
  latitude: numeric('latitude', { precision: 9, scale: 6 }),
  longitude: numeric('longitude', { precision: 9, scale: 6 }),
  accessNotes: text('access_notes'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * Property <-> Customer over time — docs/03-domain/properties.md business
 * rule 1, the load-bearing rule of the Property Intelligence pillar.
 * `effective_to IS NULL` means "current." The partial unique index
 * enforces at most one current association per Property, the same
 * pattern as `crm.contacts`' primary-Contact uniqueness.
 */
export const propertyCustomerAssociations = propertiesSchema.table(
  'property_customer_associations',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id')
      .notNull()
      .references(() => organizations.id),
    propertyId: uuid('property_id')
      .notNull()
      .references(() => properties.id),
    customerId: uuid('customer_id')
      .notNull()
      .references(() => customers.id),
    effectiveFrom: timestamp('effective_from', { withTimezone: true }).notNull().defaultNow(),
    effectiveTo: timestamp('effective_to', { withTimezone: true }),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_property_customer_associations_current')
      .on(table.propertyId)
      .where(sql`${table.effectiveTo} IS NULL`),
  ],
);

/**
 * A structure on a Property — docs/03-domain/buildings.md. Every Property
 * gets at least one (a default "Main House" Building auto-created at
 * Property creation for simple residential Properties — business rule 1);
 * that provisioning happens in the application layer
 * (@atlas/properties), not a database trigger, to keep the business rule
 * visible in reviewable TypeScript rather than implicit SQL.
 */
export const buildings = propertiesSchema.table('buildings', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  propertyId: uuid('property_id')
    .notNull()
    .references(() => properties.id),
  name: text('name').notNull(),
  buildingType: buildingTypeEnum('building_type'),
  floorCount: integer('floor_count'),
  yearBuilt: integer('year_built'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/** A discrete space within a Building — docs/03-domain/rooms.md. Optional precision layer; never required to locate an Asset. */
export const rooms = propertiesSchema.table('rooms', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  buildingId: uuid('building_id')
    .notNull()
    .references(() => buildings.id),
  name: text('name').notNull(),
  roomType: roomTypeEnum('room_type'),
  floorLevel: integer('floor_level'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});

/**
 * The trade-agnostic equipment-category configuration entity — see
 * docs/03-domain/domain-overview.md#the-trade-agnostic-configuration-pattern,
 * ADR-009. `organization_id IS NULL` means a platform-provided default,
 * visible to every Organization; a non-null value is that Organization's
 * own extension of the catalog. Org-authored custom Asset Types
 * (create/update via the app) are not implemented this sprint — see
 * docs/13-roadmap/SPRINT-3-COMPLETION-REPORT.md, "Known Limitations" —
 * only platform defaults are seeded; the table and its read API are
 * still real and ready for that extensibility to land without a schema
 * change.
 */
export const assetTypes = propertiesSchema.table(
  'asset_types',
  {
    id: uuid('id')
      .primaryKey()
      .default(sql`public.uuid_generate_v7()`),
    organizationId: uuid('organization_id').references(() => organizations.id),
    tradeTypeId: uuid('trade_type_id')
      .notNull()
      .references(() => tradeTypes.id),
    name: text('name').notNull(),
    isActive: boolean('is_active').notNull().default(true),
    createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
  },
  (table) => [
    uniqueIndex('uq_asset_types_org_trade_name').on(
      table.organizationId,
      table.tradeTypeId,
      table.name,
    ),
  ],
);

/**
 * Installed equipment tracked over its full lifecycle —
 * docs/03-domain/assets.md. `manufacturer_name`/`model_number` are plain
 * text, not a `manufacturer_id` foreign key to a shared Manufacturers
 * reference table: that table (and manufacturer-integration features
 * generally) is explicitly out of this sprint's scope, and
 * docs/04-database/foreign-keys.md requires every foreign key to be a
 * real, enforced constraint — there is no reviewed Manufacturers table
 * yet to reference. Likewise `install_job_id` is omitted entirely
 * (Jobs doesn't exist until Sprint 4) — assets.md business rule 4
 * explicitly allows an Asset to exist with no known install Job, so this
 * is the documented default state, not a gap.
 */
export const assets = propertiesSchema.table('assets', {
  id: uuid('id')
    .primaryKey()
    .default(sql`public.uuid_generate_v7()`),
  organizationId: uuid('organization_id')
    .notNull()
    .references(() => organizations.id),
  propertyId: uuid('property_id')
    .notNull()
    .references(() => properties.id),
  buildingId: uuid('building_id').references(() => buildings.id),
  roomId: uuid('room_id').references(() => rooms.id),
  assetTypeId: uuid('asset_type_id')
    .notNull()
    .references(() => assetTypes.id),
  manufacturerName: text('manufacturer_name'),
  modelNumber: text('model_number'),
  serialNumber: text('serial_number'),
  installDate: date('install_date'),
  status: assetStatusEnum('status').notNull().default('active'),
  deletedAt: timestamp('deleted_at', { withTimezone: true }),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }).notNull().defaultNow(),
});
